accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns= [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('completeProfile/<int:user_id>', views.completeProfile_view, name='completeProfile'),
]

events/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin

app_name = 'events'

urlpatterns= [
    path('', views.events, name='events'),
    path('<uuid:uuid>', views.event, name='event'),
    path('form/', views.events_form, name='events_form'),
    path('pin_event/', views.pin_event, name='pin_event'), 
    path('unpin_event/', views.unpin_event, name='unpin_event'),
    path('register_event/', views.register_event, name='register_event'),
    path('registerations/', views.registrations, name='registrations'),
]

festhub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

# Customise admin headings
admin.site.site_header = "FestHub Admin"
admin.site.site_title = "FestHub Admin Portal"
admin.site.index_title = "Welcome to FestHub Admin"


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.homepage, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('registered_events/',views.registered_events, name='registered_events'),
    
    # Event specific paths
    path('events/', include('events.urls')),
    path('committees/', include('committees.urls')),

    # Account specific paths
    path('accounts/', include('accounts.urls')),

    path('about/', views.about, name='about'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('committee/',views.committee,name='committee')
]

# Serve media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

frontend/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from profiles.models import Profile
from committees.models import Committee

# Create your forms here.

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)  # Make email field compulsory

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email',)

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True  # Set email field as required

class ProfileForm(forms.ModelForm):
    committees = forms.ModelMultipleChoiceField(queryset=Committee.objects.all(), required=False, widget=forms.CheckboxSelectMultiple)
    resume = forms.FileField(label='Resume', required=False)
    image = forms.ImageField(label='Image', required=False)
    department_year = forms.ChoiceField(choices=Profile.DEPARTMENT_YEAR_CHOICES, required=False)
    blood_group = forms.ChoiceField(choices=Profile.BLOOD_GROUP_CHOICES, required=False)

    class Meta:
        model = Profile
        fields = ['contact_number', 'address', 'birth_date', 'committees', 'resume', 'image', 'department_year', 'blood_group']  # Include blood_group in fields list
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date'}),
            'committees': forms.CheckboxSelectMultiple,
        }

accounts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate,logout
from django.contrib import messages
from .forms import CustomUserCreationForm, ProfileForm
from profiles.models import Profile
from django.contrib.auth.models import User 

def signup_view(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        if user_form.is_valid():
            username = user_form.cleaned_data.get('username')
            if CustomUserCreationForm.Meta.model.objects.filter(username=username).exists():
                messages.warning(request, 'Username already exists. Please choose a different username.')
                return redirect('accounts:signup')

            user = user_form.save()
            login(request, user) 
            messages.success(request, 'Account created successfully.')
            return redirect('accounts:completeProfile',  user_id=user.id)
        else:
            for field, errors in user_form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
    else:
        user_form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'user_form': user_form})
from django.contrib import messages

def completeProfile_view(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            if not Profile.objects.filter(user=user).exists():
                profile = profile_form.save(commit=False)
                profile.user = user
            else:
                profile = Profile.objects.get(user=user)

            profile.contact_number = profile_form.cleaned_data['contact_number']
            profile.address = profile_form.cleaned_data['address']
            profile.birth_date = profile_form.cleaned_data['birth_date']
            profile.committees.set(profile_form.cleaned_data['committees'])

            # Set optional fields
            profile.resume = request.FILES.get('resume')
            profile.image = request.FILES.get('image')
            profile.department_year = profile_form.cleaned_data['department_year']
            profile.blood_group = profile_form.cleaned_data['blood_group']

            # Check if all required fields are filled except committees
            required_fields_filled = all([
                profile.contact_number,
                profile.address,
                profile.birth_date,
            ])

            if required_fields_filled:
                profile.is_profile_complete = True
                profile.save()
                return redirect('dashboard')
            else:
                profile.is_profile_complete = False
                profile.save()
                messages.warning(request, 'Please fill all required fields to access all features.')
                return redirect('accounts:completeProfile', user_id=user_id)
        else:
            for field, errors in profile_form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
    else:
        profile_form = ProfileForm()
    return render(request, 'accounts/completeProfile.html', {'user': user, 'profile_form': profile_form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('dashboard')

    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

frontend/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/accounts/base.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Login to ResumeHub">
    <meta name="author" content="Vipul Kushwaha">
    <meta name="theme-color" content="rgba(31, 0, 59, 0.925)">

    <title>FestHub | Login</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'brand/logo.webp' %}" />

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!--Fontawesome-->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>

<body style="padding-top: 1rem; ">
    {% if messages %}
    <div class="container">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="container-fluid">

        <!--Start Content-->

        {% block page_contents %}
        {% endblock %}

        <!--End Content-->

    </div>
</body>

</html>

frontend/templates/accounts/completeProfile.html
{% extends 'base/base.html' %}
{% block main %}
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'warning' %}alert-warning{% elif message.tags == 'success' %}alert-success{% else %}alert-info{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow-lg p-4">
                <h2 class="text-center mb-4">Complete Your Profile</h2>
                <form action="{% url 'accounts:completeProfile' user.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="contact_number" class="form-label">Contact Number</label>
                        <input type="text" class="form-control" id="contact_number" name="contact_number">
                    </div>
                    <div class="mb-3">
                        <label for="resume" class="form-label">Resume</label>
                        <input type="file" class="form-control" id="resume" name="resume">
                    </div>
                    <div class="mb-3">
                        <label for="image" class="form-label">Image</label>
                        <input type="file" class="form-control" id="image" name="image">
                    </div>
                    <div class="mb-3">
                        <label for="department_year" class="form-label">Department and Year</label>
                        <select class="form-select" id="department_year" name="department_year">
                            <option value="" disabled selected>Select Department and Year</option>
                            {% for value, label in profile_form.fields.department_year.choices %}
                                <option value="{{ value }}">{{ label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="blood_group" class="form-label">Blood Group</label>
                        <select class="form-select" id="blood_group" name="blood_group">
                            <option value="" disabled selected>Select Blood Group</option>
                            {% for value, label in profile_form.fields.blood_group.choices %}
                                <option value="{{ value }}">{{ label }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <div class="mb-3">
                        <label for="address" class="form-label">Address</label>
                        <input type="text" class="form-control" id="address" name="address">
                    </div>
                    <div class="mb-3">
                        <label for="birth_date" class="form-label">Date of Birth</label>
                        <input type="date" class="form-control" id="birth_date" name="birth_date">
                    </div>
                    <div class="mb-3">
                        <label for="committees" class="form-label">Committees</label>
                        <select class="form-select" id="committees" name="committees" multiple>
                            <option value="" disabled>Select Committees</option>
                            {% for committee in profile_form.fields.committees.queryset %}
                                <option value="{{ committee.pk }}">{{ committee.name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

frontend/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block page_contents %}
{% load static %}
{% load widget_tweaks %}

<div class="row">
    <div class="col-md-6 m-1 mx-auto p-3 shadow rounded">
        <div class="page-header">
            <div class="text-left">
                <h4><i class="fa fa-sign-in" aria-hidden="true"></i> FestHub Login</h4>
            </div>
        </div>

        <form class="site-form text-center" action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <img class="my-3 mx-auto" src="{% static 'brand/logo.webp' %}" alt="logo" width="72" height="72">
            <div class="col-md-4 mx-auto">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                    <input type="text" class="form-control" name="username" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon2"><i class="fa fa-lock"></i></span>
                    <input type="password" class="form-control" name="password" id="password" placeholder="Password" aria-label="Password" aria-describedby="basic-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="togglePassword"><i class="fa fa-eye"></i></button>
                </div>
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <br>
                <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
            </div>
        </form>
        <p>Don't have an account? <a href="{% url 'accounts:signup' %}">Register here</a>.</p>
        <div class="text-center">
            <a href="{% url 'home' %}" class="text-primary-sm">Back</a>
        </div>

        <footer class="pt-2 mx-auto text-center">
            <small><span class="text-muted">Licensed to SPIT | <a href="https://festhub.spit.ac.in">FestHub</a> {% now "Y" %}</a>.
                </span>
            </small>
        </footer>
    </div>
</div>

<script>
    document.getElementById("togglePassword").addEventListener("click", function () {
        var passwordInput = document.getElementById("password");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
        } else {
            passwordInput.type = "password";
        }
    });
</script>

{% endblock %}

frontend/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% block page_contents %}
{% load static %}
{% load widget_tweaks %}

<div class="row">
    <div class="col-md-6 m-1 mx-auto p-3 shadow rounded">
        <div class="page-header">
            <div class="text-left">
                <h4><i class="fa fa-sign-in" aria-hidden="true"></i> FestHub Register</h4>
            </div>
        </div>

        <form class="site-form text-center" action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
            <img class="my-3 mx-auto" src="{% static 'brand/logo.webp' %}" alt="logo" width="72" height="72">
            <div class="col-md-4 mx-auto">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                    <input type="text" class="form-control" name="username" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon2"><i class="fa fa-envelope"></i></span>
                    <input type="email" class="form-control" name="email" placeholder="Email" aria-label="Email" aria-describedby="basic-addon2">
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon3"><i class="fa fa-lock"></i></span>
                    <input type="password" class="form-control" name="password1" id="password1" placeholder="Password" aria-label="Password" aria-describedby="basic-addon3">
                    <button class="btn btn-outline-secondary" type="button" id="togglePassword"><i class="fa fa-eye"></i></button>
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon4"><i class="fa fa-lock"></i></span>
                    <input type="password" class="form-control" name="password2" id="password2" placeholder="Confirm Password" aria-label="Confirm Password" aria-describedby="basic-addon4">
                    <button class="btn btn-outline-secondary" type="button" id="togglePassword2"><i class="fa fa-eye"></i></button>
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block">Signup</button>
            </div>
        </form>

        <p>Already have an account? <a href="{% url 'accounts:login' %}">Log in</a>.</p>
        <div class="text-center">
            <a href="{% url 'home' %}" class="text-primary-sm">Back</a>
        </div>

        <footer class="pt-2 mx-auto text-center">
            <small><span class="text-muted">Licensed to SPIT | <a href="https://festhub.spit.ac.in">FestHub</a> {% now "Y" %}</a>.</span></small>
        </footer>
    </div>
</div>

<script>
    document.getElementById("togglePassword").addEventListener("click", function () {
        var passwordInput = document.getElementById("password1");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
        } else {
            passwordInput.type = "password";
        }
    });
    document.getElementById("togglePassword2").addEventListener("click", function () {
        var passwordInput = document.getElementById("password2");
        if (passwordInput.type === "password") {
            passwordInput.type = "text";
        } else {
            passwordInput.type = "password";
        }
    });
</script>

{% endblock %}